### ISSUE TITLE
로컬 작업 시 환경설정 변경 금지를 위한 .gitignore 설정 추가

### ISSUE THREAD

**Issue by jay-so** [eodya/eodya-backend#3]
### 📝 개요
- PR 컨벤션에 따라 로컬에서 작업 시 feature/\{이슈번호}로 설정하게 됩니다. 이럴 때, bootstrap.yaml 파일의 라벨을 해당 feature/\{이슈번호}로 변경하게 되는데, 머지 시 해당 label로 머지하게 됩니다. 이를 방지하기 위한 .gitignore설정 작업입니다.

예시

```
spring:
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev 
      label: feature/1 
```

로컬에서는 위와 같이 작업은 가능하되, 본 프로젝트에서 **머지시**  label이 병합되지 않게 하기 위한 작업입니다.

---

### ✅ 작업 예정 목록
- [X] 로컬 작업 시 환경설정 변경 금지를 위한 .gitignore 설정 추가

---
